version: "3"
services:
  api:
    build: ./
    container_name: dc-esdjango
    restart: always
    env_file: ./.env
    ports:
      - 8001:8000
    volumes:
      - ./.env:/app/core/.env
    networks:
      - api_dj_es_net
    depends_on:
      - es
  es:
    image: elasticsearch:7.17.5
    container_name: elasticsearch_db
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - api_dj_es_net
    volumes:
      - es_data:/usr/share/elasticsearch/data
    

volumes:
  es_data: 
    driver: local

networks:
  api_dj_es_net:
    driver: bridge
